services:
  - type: web
    name: centrocostos-tec-api-dev
    runtime: docker
    rootDir: CentroCostosTec-API
    healthCheckPath: /api/testing/token
    envVars:
      - key: SERVER_PORT
        value: 10000
      - key: APP_CORS_ALLOWED_ORIGINS
        value: https://centrocostos-tec-front.web.app,https://centrocostos-tec-front.firebaseapp.com,http://localhost:4200
      - key: APP_ACCOUNT_VERIFY_URL
        value: https://centrocostos-tec-front.web.app/verificar-cuenta
      - key: APP_JWT_SECRET
        sync: false
      - key: APP_DB_URL
        value: jdbc:postgresql://dpg-d86bq4t7vvec73dki9vg-a/pida_dev
      - key: APP_DB_USER
        sync: false
      - key: APP_DB_PASSWORD
        sync: false
      - key: APP_MAIL_HOST
        value: smtp.gmail.com
      - key: APP_MAIL_PORT
        value: 587
      - key: APP_MAIL_USER
        sync: false
      - key: APP_MAIL_PASS
        sync: false
      - key: APP_MAIL_FROM
        sync: false

databases:
  - name: centrocostos-tec-db-dev
    databaseName: pida_dev
    user: pida_dev_user
