export const ESTADOS_MX: string[] = [
  'Aguascalientes',
  'Baja California',
  'Baja California Sur',
  'Campeche',
  'Chiapas',
  'Chihuahua',
  'Ciudad de Mexico',
  'Coahuila',
  'Colima',
  'Durango',
  'Estado de Mexico',
  'Guanajuato',
  'Guerrero',
  'Hidalgo',
  'Jalisco',
  'Michoacan',
  'Morelos',
  'Nayarit',
  'Nuevo Leon',
  'Oaxaca',
  'Puebla',
  'Queretaro',
  'Quintana Roo',
  'San Luis Potosi',
  'Sinaloa',
  'Sonora',
  'Tabasco',
  'Tamaulipas',
  'Tlaxcala',
  'Veracruz',
  'Yucatan',
  'Zacatecas',
];

export const MUNICIPIOS_POR_ESTADO: Record<string, string[]> = {
  'Aguascalientes': [
    'Aguascalientes',
    'Asientos',
    'Calvillo',
    'Cosio',
    'Jesus Maria',
    'Pabellon de Arteaga',
    'Rincon de Romos',
    'San Francisco de los Romo',
    'Tepezala',
  ],
  'Baja California': [
    'Ensenada',
    'Mexicali',
    'Playas de Rosarito',
    'Rodolfo Sanchez T. (Maneadero)',
    'San Felipe',
    'Tecate',
    'Tijuana',
  ],
  'Baja California Sur': [
    'Cabo San Lucas',
    'Ciudad Constitucion',
    'Guerrero Negro',
    'Heroica Mulege',
    'La Paz',
    'Loreto',
    'Puerto Adolfo Lopez Mateos',
    'San Ignacio',
    'San Jose del Cabo',
    'Santa Rosalia',
    'Todos Santos',
    'Villa Alberto Andres Alvarado Aramburo',
  ],
  'Campeche': [
    'Calkini',
    'Candelaria',
    'Champoton',
    'Ciudad del Carmen',
    'Escarcega',
    'Hecelchakan',
    'Hopelchen',
    'Pomuch',
    'Sabancuy',
    'San Francisco de Campeche',
  ],
  'Chiapas': [
    'Acala',
    'Arriaga',
    'Cacahoatan',
    'Chiapa de Corzo',
    'Cintalapa de Figueroa',
    'Comitan de Dominguez',
    'Huixtla',
    'Jiquipilas',
    'Las Margaritas',
    'Las Rosas',
    'Mapastepec',
    'Motozintla de Mendoza',
    'Ocosingo',
    'Ocozocoautla de Espinosa',
    'Palenque',
    'Pichucalco',
    'Pijijiapan',
    'Puerto Madero (San Benito)',
    'Reforma',
    'San Cristobal de las Casas',
    'Tapachula de Cordova y Ordonez',
    'Tonala',
    'Tuxtla Gutierrez',
    'Venustiano Carranza',
    'Villaflores',
  ],
  'Chihuahua': [
    'Bachiniva',
    'Chihuahua',
    'Colonia Anahuac',
    'Cuauhtemoc',
    'Delicias',
    'Hidalgo del Parral',
    'Jose Mariano Jimenez',
    'Juan Aldama',
    'Juarez',
    'Madera',
    'Manuel Ojinaga',
    'Nuevo Casas Grandes',
    'Santa Rosalia de Camargo',
    'Saucillo',
  ],
  'Ciudad de Mexico': [
    'Ciudad de Mexico',
  ],
  'Coahuila': [
    'Allende',
    'Arteaga',
    'Castanos',
    'Ciudad Acuna',
    'Ciudad Melchor Muzquiz',
    'Cuatro Cienegas de Carranza',
    'Francisco I. Madero (Chavez)',
    'Frontera',
    'Matamoros',
    'Monclova',
    'Morelos',
    'Nadadores',
    'Nava',
    'Nueva Rosita',
    'Parras de la Fuente',
    'Piedras Negras',
    'Ramos Arizpe',
    'Sabinas',
    'Saltillo',
    'San Buenaventura',
    'San Pedro',
    'Torreon',
    'Viesca',
    'Zaragoza',
  ],
  'Colima': [
    'Ciudad de Armeria',
    'Ciudad de Villa de Alvarez',
    'Colima',
    'Manzanillo',
    'Tecoman',
  ],
  'Durango': [
    'Canatlan',
    'Ciudad Lerdo',
    'El Salto',
    'Francisco I. Madero',
    'Gomez Palacio',
    'Nombre de Dios',
    'Penon Blanco',
    'San Juan del Rio del Centauro del Norte',
    'Santa Maria del Oro',
    'Santiago Papasquiaro',
    'Vicente Guerrero',
    'Victoria de Durango',
  ],
  'Estado de Mexico': [
    'Almoloya de Juarez',
    'Amatepec',
    'Capulhuac',
    'Chalco de Diaz Covarrubias',
    'Chiconcuac',
    'Chimalhuacan',
    'Ciudad Adolfo Lopez Mateos',
    'Ciudad Nezahualcoyotl',
    'Coacalco de Berriozabal',
    'Cuautitlan',
    'Cuautitlan Izcalli',
    'Ecatepec de Morelos',
    'Huixquilucan de Degollado',
    'Ixtapaluca',
    'Juchitepec de Mariano Riva Palacio',
    'Los Reyes Acaquilpan (La Paz)',
    'Melchor Ocampo',
    'Metepec',
    'Naucalpan de Juarez',
    'Ocoyoacac',
    'San Mateo Atenco',
    'San Vicente Chicoloapan de Juarez',
    'Santa Maria Tultepec',
    'Tecamac de Felipe Villanueva',
    'Tejupilco de Hidalgo',
    'Tepotzotlan',
    'Tequixquiac',
    'Texcoco de Mora',
    'Tlalnepantla de Baz',
    'Toluca de Lerdo',
    'Tultitlan de Mariano Escobedo',
    'Valle de Chalco Solidaridad',
    'Villa Nicolas Romero',
    'Xonacatlan',
    'Zumpango',
  ],
  'Guanajuato': [
    'Abasolo',
    'Acambaro',
    'Apaseo el Alto',
    'Apaseo el Grande',
    'Celaya',
    'Ciudad Manuel Doblado',
    'Comonfort',
    'Cortazar',
    'Cueramaro',
    'Doctor Mora',
    'Dolores Hgo. Cuna de la Indep. Nal.',
    'Empalme Escobedo (Escobedo)',
    'Guanajuato',
    'Huanimaro',
    'Irapuato',
    'Jaral del Progreso',
    'Jerecuaro',
    'Leon de los Aldama',
    'Marfil',
    'Moroleon',
    'Penjamo',
    'Purisima de Bustos',
    'Rincon de Tamayo',
    'Romita',
    'Salamanca',
    'Salvatierra',
    'San Diego de la Union',
    'San Francisco del Rincon',
    'San Jose Iturbide',
    'San Luis de la Paz',
    'San miguel de Allende',
    'Santa Cruz Juventino Rosas',
    'Santiago Maravatio',
    'Silao',
    'Tarandacuao',
    'Uriangato',
    'Valle de Santiago',
    'Villagran',
    'Yuriria',
  ],
  'Guerrero': [
    'Acapulco de Juarez',
    'Arcelia',
    'Atoyac de Alvarez',
    'Ayutla de los Libres',
    'Azoyu',
    'Buenavista de Cuellar',
    'Chilapa de Alvarez',
    'Chilpancingo de los Bravo',
    'Ciudad Altamirano',
    'Ciudad Apaxtla de Castrejon',
    'Copala',
    'Coyuca de Benitez',
    'Coyuca de Catalan',
    'Cruz Grande',
    'Cuajinicuilapa',
    'Cutzamala de Pinzon',
    'Huamuxtitlan',
    'Huitzuco',
    'Iguala de la Independencia',
    'La Union',
    'Marquelia',
    'Ocotito',
    'Olinala',
    'Petatlan',
    'San Jeronimo de Juarez',
    'San Luis Acatlan',
    'San Luis San Pedro',
    'San Luis de la Loma',
    'San Marcos',
    'Taxco de Alarcon',
    'Tecpan de Galeana',
    'Teloloapan',
    'Tepecoacuilco de Trujano',
    'Tierra Colorada',
    'Tixtla de Guerrero',
    'Tlalixtaquilla',
    'Tlapa de Comonfort',
    'Tlapehuala',
    'Zihuatanejo',
    'Zumpango del Rio',
  ],
  'Hidalgo': [
    'Actopan',
    'Apan',
    'Cd. de Fray Bernardino de Sahagun',
    'Cruz Azul',
    'Huejutla de Reyes',
    'Ixmiquilpan',
    'Pachuca de Soto',
    'Santiago Tulantepec',
    'Tepeapulco',
    'Tepeji del Rio',
    'Tizayuca',
    'Tlaxcoapan',
    'Tula de Allende',
    'Tulancingo',
    'Zimapan',
  ],
  'Jalisco': [
    'Acatlan de Juarez',
    'Ahualulco de Mercado',
    'Ajijic',
    'Ameca',
    'Arandas',
    'Atotonilco el Alto',
    'Autlan de Navarro',
    'Chapala',
    'Cihuatlan',
    'Ciudad Guzman',
    'Cocula',
    'Colotlan',
    'El Grullo',
    'El Quince (San Jose el Quince)',
    'Etzatlan',
    'Guadalajara',
    'Huejuquilla el Alto',
    'Jalostotitlan',
    'Jamay',
    'Jocotepec',
    'La Barca',
    'La Resolana',
    'Lagos de Moreno',
    'Las Pintitas',
    'Magdalena',
    'Ocotlan',
    'Poncitlan',
    'Puerto Vallarta',
    'San Diego de Alejandria',
    'San Ignacio Cerro Gordo',
    'San Jose el Verde (El Verde)',
    'San Juan de los Lagos',
    'San Julian',
    'San Miguel el Alto',
    'Sayula',
    'Tala',
    'Talpa de Allende',
    'Tamazula de Gordiano',
    'Tecalitlan',
    'Teocaltiche',
    'Tepatitlan de Morelos',
    'Tequila',
    'Tlajomulco de Zuniga',
    'Tlaquepaque',
    'Tonala',
    'Tototlan',
    'Tuxpan',
    'Union de San Antonio',
    'Valle de Guadalupe',
    'Villa Corona',
    'Villa Hidalgo',
    'Yahualica de Gonzalez Gallo',
    'Zacoalco de Torres',
    'Zapopan',
    'Zapotiltic',
  ],
  'Michoacan': [
    'Apatzingan de la Constitucion',
    'Ciudad Hidalgo',
    'Ciudad Lazaro Cardenas',
    'Cotija de la Paz',
    'Cuitzeo del Porvenir',
    'Heroica Zitacuaro',
    'Huetamo de Nunez',
    'Jacona de Plancarte',
    'Jiquilpan de Juarez',
    'La piedad de Cabadas',
    'Las Guacamayas',
    'Los Reyes de Salgado',
    'Maravatio de Ocampo',
    'Morelia',
    'Nueva Italia de Ruiz',
    'Paracho de Verduzco',
    'Patzcuaro',
    'Puruandiro',
    'Sahuayo de Morelos',
    'Tacambaro de Codallos',
    'Tangancicuaro de Arista',
    'Tuxpan',
    'Uruapan',
    'Yurecuaro',
    'Zacapu',
    'Zamora de Hidalgo',
    'Zinapecuaro de Figueroa',
  ],
  'Morelos': [
    'Cuautla (Cuautla de Morelos)',
    'Cuernavaca',
    'Galeana',
    'Jojutla',
    'Puente de Ixtla',
    'Santa Rosa Treinta',
    'Tlaquiltenango',
    'Zacatepec de Hidalgo',
  ],
  'Nayarit': [
    'Acaponeta',
    'Ahuacatlan',
    'Bucerias',
    'Compostela',
    'Francisco I. Madero (Puga)',
    'Ixtlan del Rio',
    'Jala',
    'La penita de Jaltemba',
    'Las Varas',
    'Ruiz',
    'San Blas',
    'San pedro Lagunillas',
    'Santiago Ixcuintla',
    'Tecuala',
    'Tepic',
    'Tuxpan',
    'Villa Hidalgo (El Nuevo)',
    'Xalisco',
  ],
  'Nuevo Leon': [
    'Anahuac',
    'Cadereyta Jimenez',
    'Cienega de Flores',
    'Ciudad Apodaca',
    'Ciudad Benito Juarez',
    'Ciudad General Escobedo',
    'Ciudad Sabinas Hidalgo',
    'Ciudad Santa Catarina',
    'Doctor Arroyo',
    'El cercado',
    'Garcia',
    'Guadalupe',
    'Hualahuises',
    'Linares',
    'Montemorelos',
    'Monterrey',
    'San Nicolas de los Garza',
    'San Pedro Garza Garcia',
    'Santiago',
  ],
  'Oaxaca': [
    'Asuncion Nochixtlan',
    'Bahias de Huatulco',
    'Chahuites',
    'Ciudad Ixtepec',
    'Cosolapa',
    'Cuilapam de Guerrero',
    'El Camaron',
    'El Rosario',
    'Heroica Ciudad de Ejutla de Crespo',
    'Heroica Ciudad de Huajuapan de Leon',
    'Heroica Ciudad de Tlaxiaco',
    'Juchitan (Juchitan de Zaragoza)',
    'Lagunas',
    'Loma Bonita',
    'Mariscala de Juarez',
    'Matias Romero Avendano',
    'Miahuatlan de Porfirio Diaz',
    'Natividad',
    'Oaxaca de Juarez',
    'Ocotlan de Morelos',
    'Puerto Escondido',
    'Putla Villa de Guerrero',
    'Rio Grande o Piedra Parada',
    'Salina Cruz',
    'San Antonio de la Cal',
    'San Blas Atempa',
    'San Felipe Jalapa de Diaz',
    'San Francisco Ixhuatan',
    'San Francisco Telixtlahuaca',
    'San Juan Bautista Cuicatlan',
    'San Juan Bautista Tuxtepec',
    'San Juan Bautista Valle Nacional',
    'San Juan Bautista lo de Soto',
    'San Juan Cacahuatepec',
    'San Miguel el Grande',
    'San Pablo Huitzo',
    'San Pablo Villa de Mitla',
    'San Pedro Mixtepec -Dto. 22-',
    'San Pedro Pochutla',
    'San Pedro Tapanatepec',
    'San Pedro Totolapa',
    'San Sebastian Tecomaxtlahuaca',
    'Santa Cruz Itundujia',
    'Santa Lucia del Camino',
    'Santa Maria Huatulco',
    'Santiago Jamiltepec',
    'Santiago Juxtlahuaca',
    'Santiago Pinotepa Nacional',
    'Santiago Suchilquitongo',
    'Santo Domingo Tehuantepec',
    'Teotitlan de Flores Magon',
    'Tlacolula de Matamoros',
    'Union Hidalgo',
    'Vicente Camalote',
    'Villa Sola de Vega',
    'Villa de Tamazulapam del Progreso',
    'Villa de Zaachila',
    'Zimatlan de Alvarez',
  ],
  'Puebla': [
    'Acatlan de Osorio',
    'Amozoc',
    'Atlixco',
    'Ciudad Serdan',
    'Cuautlancingo',
    'Huauchinango',
    'Izucar de Matamoros',
    'Puebla (Heroica Puebla)',
    'San Andres Cholula',
    'San Martin Texmelucan de Labastida',
    'San Pedro Cholula',
    'Tecamachalco',
    'Tehuacan',
    'Tepeaca',
    'Teziutlan',
    'Xicotepec',
    'Zacatlan',
  ],
  'Queretaro': [
    'El Pueblito',
    'Queretaro',
    'San Juan del Rio',
  ],
  'Quintana Roo': [
    'Bacalar',
    'Cancun',
    'Chetumal',
    'Cozumel',
    'Felipe Carrillo Puerto',
    'Isla Mujeres',
    'Kantunilkin',
    'Playa del Carmen',
  ],
  'San Luis Potosi': [
    'Cardenas',
    'Cedral',
    'Cerritos',
    'Charcas',
    'Ciudad Valles',
    'Ciudad del Maiz',
    'Ebano',
    'El Naranjo',
    'Fraccion el Refugio',
    'Matehuala',
    'Rioverde',
    'Salinas de Hidalgo',
    'San Luis Potosi',
    'Santa Maria del Rio',
    'Soledad de Graciano Sanchez',
    'Tamasopo',
    'Tamazunchale',
    'Tamuin',
    'Tierra Nueva',
    'Villa de Reyes',
  ],
  'Sinaloa': [
    'Aguaruto',
    'Ahome',
    'Angostura',
    'Choix',
    'Cosala',
    'Culiacan Rosales',
    'El rosario',
    'Escuinapa de Hidalgo',
    'Estacion Naranjo',
    'Guamuchil',
    'Guasave',
    'Higuera de Zaragoza',
    'La Cruz',
    'Lic. Benito Juarez (Campo Gobierno)',
    'Los Mochis',
    'Mazatlan',
    'Mocorito',
    'Navolato',
    'Quila',
    'San Blas',
    'San Ignacio',
    'Sinaloa de Leyva',
    'Topolobampo',
    'Villa Union',
  ],
  'Sonora': [
    'Agua Prieta',
    'Ciudad Obregon',
    'Empalme',
    'Hermosillo',
    'Heroica Caborca',
    'Heroica Ciudad de Cananea',
    'Heroica Guaymas',
    'Heroica Nogales',
    'Huatabampo',
    'Magdalena de Kino',
    'Navojoa',
    'Puerto Penasco',
    'San Luis Rio Colorado',
    'Sonoita',
  ],
  'Tabasco': [
    'Cardenas',
    'Comalcalco',
    'Cunduacan',
    'Emiliano Zapata',
    'Frontera',
    'Huimanguillo',
    'Jalpa de Mendez',
    'Macuspana',
    'Paraiso',
    'Teapa',
    'Tenosique de Pino Suarez',
    'Villahermosa',
  ],
  'Tamaulipas': [
    'Altamira',
    'Ciudad Camargo',
    'Ciudad Gustavo Diaz Ordaz',
    'Ciudad Madero',
    'Ciudad Mante',
    'Ciudad Miguel Aleman',
    'Ciudad Rio Bravo',
    'Ciudad Tula',
    'Ciudad Victoria',
    'Estacion Manuel (Ursulo Galvan)',
    'Gonzalez',
    'Heroica Matamoros',
    'Jaumave',
    'Nueva Ciudad Guerrero',
    'Nuevo Laredo',
    'Reynosa',
    'San Fernando',
    'Soto la Marina',
    'Tampico',
    'Valle Hermoso',
    'Xicotencatl',
  ],
  'Tlaxcala': [
    'Apizaco',
    'Calpulalpan',
    'Chiautempan',
    'Huamantla',
    'Tlaxcala (Tlaxcala de Xicotencatl)',
    'Villa Vicente Guerrero',
  ],
  'Veracruz': [
    'Acayucan',
    'Agua dulce',
    'Altotonga',
    'Alvarado',
    'Atoyac',
    'Banderilla',
    'Boca del RIo',
    'Carlos A. Carrillo',
    'Catemaco',
    'Cazones de Herrera',
    'Cerro Azul',
    'Coatepec',
    'Coatzacoalcos',
    'Coatzintla',
    'Cordoba',
    'Cosamaloapan',
    'Cosoleacaque',
    'Cuichapa',
    'Cuitlahuac',
    'El Higo',
    'Fortin de las Flores',
    'General Miguel Aleman (Potrero Nuevo)',
    'Gutierrez Zamora',
    'Huatusco de Chicuellar',
    'Huayacocotla',
    'Huiloapan de Cuauhtemoc',
    'Isla',
    'Ixtaczoquitlan',
    'Jaltipan de Morelos',
    'Jose Cardel',
    'Juan Diaz Covarrubias',
    'Juan Rodriguez Clara',
    'Las Choapas',
    'Lerdo de Tejada',
    'Minatitlan',
    'Naranjos',
    'Nogales',
    'Orizaba',
    'Panuco',
    'Papantla de Olarte',
    'Paraje Nuevo',
    'Paso de Ovejas',
    'Paso del Macho',
    'Platon Sanchez',
    'Playa Vicente',
    'Poza Rica de Hidalgo',
    'Rio Blanco',
    'San Andres Tuxtla',
    'San Rafael',
    'Santiago Tuxtla',
    'Sihuapan',
    'Soledad de Doblado',
    'Tampico Alto',
    'Tantoyuca',
    'Tempoal de Sanchez',
    'Tezonapa',
    'Tierra Blanca',
    'Tihuatlan',
    'Tlacojalpan',
    'Tlapacoyan',
    'Tres Valles',
    'Tuxpam de Rodriguez Cano',
    'Veracruz',
    'Xalapa-Enriquez',
    'Yecuatla',
    'mendoza',
  ],
  'Yucatan': [
    'Kanasin',
    'Merida',
    'Motul de Carrillo Puerto',
    'Ticul',
    'Tizimin',
    'Valladolid',
  ],
  'Zacatecas': [
    'Ciudad Cuauhtemoc',
    'Fresnillo',
    'Guadalupe',
    'Jalpa',
    'Jerez de Garcia Salinas',
    'Juan Aldama',
    'Loreto',
    'Luis Moya',
    'Moyahua de Estrada',
    'Nochistlan de Mejia',
    'Ojocaliente',
    'Rio Grande',
    'Sombrerete',
    'Valparaiso',
    'Victor Rosales',
    'Villa Hidalgo',
    'Villa de Cos',
    'Villanueva',
    'Zacatecas',
  ],
};

// El mapa completo CP->colonias vive en src/assets/catalogos/cp-colonias.json
// para no inflar el bundle de JS en tiempo de compilacion.